@startuml main drone

start

while (Mod değiştir veya yeni bağlantı kur?) is (evet)
:Kontrol istasyonuna bağlan;
while (Bağlantı kuruldu mu?) is (hayır)
endwhile (evet)
:Kontrol istasyonuna veri gönderimini başlat;
:Seçili modu başlat (otonom/manuel/acil durum);
endwhile (hayır)

stop
@enduml
